# Generated by Django 5.2.4 on 2025-07-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[(1, "正常"), (0, "删除")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "is_nav",
                    models.BooleanField(default=False, verbose_name="是否为导航"),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                (
                    "desc",
                    models.CharField(blank=True, max_length=1024, verbose_name="摘要"),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="正文必须为 Markdown 格式", verbose_name="正文"
                    ),
                ),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[(1, "正常"), (0, "删除")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="covers/", verbose_name="封面"
                    ),
                ),
                ("pv", models.PositiveIntegerField(default=0, verbose_name="页面访问")),
                ("uv", models.PositiveIntegerField(default=0, verbose_name="用户访问")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="上次修改时间"),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="PostVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=64)),
                (
                    "visit_type",
                    models.PositiveIntegerField(
                        choices=[(0, "用户访问"), (1, "页面访问")],
                        default=0,
                        verbose_name="访问模式",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[(1, "正常"), (0, "删除")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "is_nav",
                    models.BooleanField(default=False, verbose_name="是否为导航"),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
            },
        ),
    ]
