# Generated by Django 5.1.5 on 2025-02-10 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blogs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "分类", "verbose_name_plural": "分类"},
        ),
        migrations.RenameField(
            model_name="category",
            old_name="add_time",
            new_name="created_time",
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.AddField(
            model_name="category",
            name="is_nav",
            field=models.BooleanField(default=False, verbose_name="是否为导航"),
        ),
        migrations.AddField(
            model_name="category",
            name="owner",
            field=models.ForeignKey(
                default="714",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="status",
            field=models.PositiveIntegerField(
                choices=[(1, "正常"), (0, "删除")], default=1, verbose_name="状态"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, verbose_name="名称"),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[(1, "正常"), (0, "删除")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "is_nav",
                    models.BooleanField(default=False, verbose_name="是否为导航"),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                (
                    "desc",
                    models.CharField(blank=True, max_length=1024, verbose_name="摘要"),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="正文必须为 Markdown 格式", verbose_name="正文"
                    ),
                ),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[(1, "正常"), (0, "删除")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="上次修改时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Blogs.category",
                        verbose_name="分类",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Blogs.tag",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
                "ordering": ["-created_time"],
            },
        ),
        migrations.DeleteModel(
            name="Article",
        ),
    ]
