# Generated by Django 5.1.5 on 2026-06-21 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blogs", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="visibility",
            field=models.PositiveIntegerField(
                choices=[(0, "公开"), (1, "仅 staff 可见")],
                default=0,
                verbose_name="可见性",
            ),
        ),
        migrations.CreateModel(
            name="PostRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "major",
                    models.PositiveSmallIntegerField(default=1, verbose_name="大版本"),
                ),
                (
                    "minor",
                    models.PositiveSmallIntegerField(default=0, verbose_name="小修订"),
                ),
                (
                    "version",
                    models.CharField(
                        editable=False, max_length=16, verbose_name="版本号"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题快照")),
                (
                    "desc",
                    models.CharField(
                        blank=True, max_length=1024, verbose_name="摘要快照"
                    ),
                ),
                ("content", models.TextField(verbose_name="正文快照")),
                ("slug", models.SlugField(max_length=255, verbose_name="slug快照")),
                (
                    "change_type",
                    models.CharField(
                        choices=[("major", "大版本"), ("minor", "小修订")],
                        max_length=16,
                        verbose_name="变更类型",
                    ),
                ),
                (
                    "edit_summary",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="编辑摘要"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="快照时间"),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="编辑者",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="Blogs.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章修订",
                "verbose_name_plural": "文章修订",
                "ordering": ["-major", "-minor"],
                "unique_together": {("post", "major", "minor")},
            },
        ),
    ]
