# Generated by Django 5.1.5 on 2025-02-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blogs", "0002_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pv",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="post",
            name="uv",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
