# Generated by Django 5.1.5 on 2026-06-21 18:00

from django.db import migrations


def create_v1_snapshots(apps, schema_editor):
    """为所有 STATUS_NORMAL 的文章创建 v1.0 初始快照"""
    Post = apps.get_model('Blogs', 'Post')
    PostRevision = apps.get_model('Blogs', 'PostRevision')

    revision_count = 0
    for post in Post.objects.filter(status=1):  # STATUS_NORMAL
        PostRevision.objects.create(
            post=post,
            major=1, minor=0, version="1.0",
            title=post.title,
            desc=post.desc,
            content=post.content,
            slug=post.slug,
            editor=post.owner,
            change_type='major',
            edit_summary='初始发布',
        )
        revision_count += 1

    if revision_count:
        print(f"  → 为 {revision_count} 篇文章创建 v1.0 初始快照")


def reverse_migration(apps, schema_editor):
    """回滚：删除所有 PostRevision 记录"""
    PostRevision = apps.get_model('Blogs', 'PostRevision')
    PostRevision.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("Blogs", "0003_post_visibility_postrevision"),
    ]

    operations = [
        migrations.RunPython(create_v1_snapshots, reverse_migration),
    ]
