# Generated by Django 5.1.5 on 2026-06-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blogs", "0004_create_initial_revisions"),
    ]

    operations = [
        migrations.AddField(
            model_name="postrevision",
            name="diff_from_previous",
            field=models.TextField(
                blank=True, null=True, verbose_name="与上一版本差异"
            ),
        ),
    ]
