# Generated by Django 5.1.5 on 2026-06-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blogs", "0005_add_diff_from_previous"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "permissions": [("manage_category", "可管理分类")],
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_time"],
                "permissions": [
                    ("publish_post", "可发布/下架文章"),
                    ("review_post", "可审核文章内容"),
                ],
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "permissions": [("manage_tag", "可管理标签")],
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.PositiveIntegerField(
                choices=[(0, "删除"), (1, "已发布"), (2, "草稿"), (3, "审核中")],
                default=1,
                verbose_name="状态",
            ),
        ),
    ]
