# Generated by Django 5.1.5 on 2026-06-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="is_reviewer",
            field=models.BooleanField(default=False, verbose_name="内容审核权限"),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="账号启用"),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="is_dashboard_user",
            field=models.BooleanField(default=False, verbose_name="仪表盘入口"),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="超级管理员入口"),
        ),
    ]
