# Generated by Django 5.1.5 on 2026-07-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': [('manage_user_accounts', '可管理用户账号')]},
        ),
    ]
