# Generated by Django 5.1.5 on 2026-07-26 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_initialize_global_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='MfaTotpDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待确认'), ('active', '已启用'), ('revoked', '已撤销')], default='pending', max_length=8, verbose_name='状态')),
                ('secret_ciphertext', models.BinaryField(verbose_name='种子密文')),
                ('secret_nonce', models.BinaryField(verbose_name='加密随机数')),
                ('key_id', models.CharField(editable=False, max_length=32, verbose_name='密钥版本')),
                ('binding_expires_at', models.DateTimeField(verbose_name='绑定过期时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('last_accepted_step', models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='最后接受的时间步')),
                ('auth_version', models.PositiveIntegerField(default=1, editable=False, verbose_name='认证版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_totp_device', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'TOTP 设备',
                'verbose_name_plural': 'TOTP 设备',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', True), ('revoked_at__isnull', True), ('status', 'pending')), models.Q(('confirmed_at__isnull', False), ('revoked_at__isnull', True), ('status', 'active')), models.Q(('revoked_at__isnull', False), ('status', 'revoked')), _connector='OR'), name='accounts_mfa_totp_status_dates_valid'), models.CheckConstraint(condition=models.Q(('auth_version__gte', 1)), name='accounts_mfa_totp_auth_version_gte_1'), models.CheckConstraint(condition=models.Q(('last_accepted_step__isnull', True), ('last_accepted_step__gte', 0), _connector='OR'), name='accounts_mfa_totp_step_nonnegative')],
            },
        ),
    ]
