# Generated by Django 5.1.5 on 2026-07-28 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_mfatotpdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MfaRecoveryCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_digest', models.CharField(editable=False, max_length=128, verbose_name='恢复码哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to='accounts.mfatotpdevice', verbose_name='TOTP 设备')),
            ],
            options={
                'verbose_name': 'MFA 恢复码',
                'verbose_name_plural': 'MFA 恢复码',
                'indexes': [models.Index(fields=['device', 'used_at'], name='accounts_mf_device__026f30_idx')],
            },
        ),
    ]
