# Generated by Django 5.1.5 on 2026-07-28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_mfarecoverycode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientCertificateBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        editable=False, max_length=128, verbose_name="证书序列号"
                    ),
                ),
                (
                    "issuer_dn",
                    models.TextField(editable=False, verbose_name="签发者 DN"),
                ),
                (
                    "issuer_dn_sm3",
                    models.CharField(
                        editable=False, max_length=64, verbose_name="签发者 SM3 摘要"
                    ),
                ),
                (
                    "subject_dn",
                    models.TextField(editable=False, verbose_name="Subject DN"),
                ),
                (
                    "certificate_profile",
                    models.CharField(
                        choices=[
                            ("standard-tls", "标准 TLS"),
                            ("sm2-tlcp", "SM2 / TLCP"),
                        ],
                        editable=False,
                        max_length=16,
                        verbose_name="证书协议档案",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "已启用"), ("revoked", "已撤销")],
                        default="active",
                        editable=False,
                        max_length=8,
                        verbose_name="状态",
                    ),
                ),
                (
                    "auth_version",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="认证版本"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(editable=False, verbose_name="证书到期时间"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(editable=False, verbose_name="绑定时间"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="撤销时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_certificate_bindings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="超级管理员",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户端证书绑定",
                "verbose_name_plural": "客户端证书绑定",
                "indexes": [
                    models.Index(
                        fields=["user", "status", "expires_at"],
                        name="accounts_cl_user_id_e24f0a_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("issuer_dn_sm3", "serial_number"),
                        name="accounts_cert_issuer_serial_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("auth_version__gte", 1)),
                        name="accounts_cert_auth_version_gte_1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("revoked_at__isnull", True), ("status", "active")
                            ),
                            models.Q(
                                ("revoked_at__isnull", False), ("status", "revoked")
                            ),
                            _connector="OR",
                        ),
                        name="accounts_cert_status_date_valid",
                    ),
                ],
            },
        ),
    ]
