# Generated by Django 5.2.4 on 2025-08-02 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hmac", models.CharField(max_length=128)),
                ("is_tampered", models.BooleanField(default=False)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "log_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="admin.logentry"
                    ),
                ),
            ],
            options={
                "verbose_name": "日志完整性记录",
                "verbose_name_plural": "日志完整性记录",
                "indexes": [
                    models.Index(
                        fields=["is_tampered"], name="security_se_is_tamp_519340_idx"
                    ),
                    models.Index(
                        fields=["computed_at"], name="security_se_compute_3d15d5_idx"
                    ),
                ],
            },
        ),
    ]
