# Generated by Django 5.1.5 on 2025-09-01 21:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0002_remove_comment_image_alter_comment_nickname_and_more"),
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (1, "创建评论"),
                            (2, "编辑评论"),
                            (3, "删除评论"),
                            (0, "审核操作"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "action_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.TextField()),
                ("referrer", models.TextField(blank=True, null=True)),
                ("url_path", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "client_fingerprint",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("comment_snapshot", models.JSONField()),
                (
                    "record_hash",
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                (
                    "prev_record_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("chain_head_key", models.CharField(db_index=True, max_length=64)),
                (
                    "masked_ip",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="comment.comment",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论事件日志",
                "verbose_name_plural": "评论事件日志",
                "indexes": [
                    models.Index(
                        fields=["action_at"], name="security_co_action__bbcf54_idx"
                    ),
                    models.Index(
                        fields=["chain_head_key", "id"],
                        name="security_co_chain_h_ccaa13_idx",
                    ),
                ],
            },
        ),
    ]
