# Generated by Django 5.1.5 on 2026-07-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_delete_commenteventlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securelogentry',
            options={'permissions': [('view_audit_log', '可查看安全审计日志'), ('run_integrity_audit', '可运行日志完整性审计')], 'verbose_name': '日志完整性记录', 'verbose_name_plural': '日志完整性记录'},
        ),
    ]
