# Generated by Django 5.1.5 on 2026-06-22 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Blogs", "0005_add_diff_from_previous"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=64, unique=True, verbose_name="标识符"),
                ),
                ("name", models.CharField(max_length=64, verbose_name="板块名称")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="支持 HTML，用于 editorial-body",
                        verbose_name="描述",
                    ),
                ),
                (
                    "glitch_color",
                    models.CharField(
                        default="#4ed7af",
                        help_text="鼠标悬停 editorial-visual 时的颜色叠加，CSS 颜色值",
                        max_length=32,
                        verbose_name="Glitch 颜色",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="逗号分隔，竖排展示在第四栏",
                        max_length=256,
                        verbose_name="关键词",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="数字越小越靠前", verbose_name="排序"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="点击 Enter World 跳转到该分类文章列表",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Blogs.category",
                        verbose_name="关联分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "首页板块",
                "verbose_name_plural": "首页板块",
                "ordering": ["sort_order", "pk"],
            },
        ),
    ]
