# Generated by Django 5.1.5 on 2026-07-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("contributor", "投稿者"),
                            ("editor", "编辑者"),
                            ("reviewer", "审核者"),
                            ("manager", "板块管理员"),
                        ],
                        max_length=16,
                        verbose_name="板块角色",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="boards.board",
                        verbose_name="板块",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="自动迁移或系统初始化的记录可以为空。",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_board_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "板块成员",
                "verbose_name_plural": "板块成员",
                "ordering": ["board_id", "user_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("board", "user"),
                        name="unique_board_member",
                    )
                ],
            },
        ),
    ]
