# Generated by Django 5.1.5 on 2026-07-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_boardmembership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['sort_order', 'pk'], 'permissions': [('apply_board_access', '可申请板块权限')], 'verbose_name': '首页板块', 'verbose_name_plural': '首页板块'},
        ),
    ]
