# Generated by Django 5.1.5 on 2026-07-26 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_board_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('contributor', '投稿者'), ('editor', '编辑者'), ('reviewer', '审核者'), ('manager', '板块管理员')], max_length=16, verbose_name='申请角色')),
                ('reason', models.TextField(blank=True, verbose_name='申请说明')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已驳回')], default='pending', max_length=16, verbose_name='状态')),
                ('previous_role', models.CharField(blank=True, choices=[('contributor', '投稿者'), ('editor', '编辑者'), ('reviewer', '审核者'), ('manager', '板块管理员')], max_length=16, verbose_name='审核时原角色')),
                ('decision_note', models.TextField(blank=True, verbose_name='审核说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_access_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='boards.board', verbose_name='板块')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_board_access_requests', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '板块权限申请',
                'verbose_name_plural': '板块权限申请',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('board', 'applicant'), name='unique_pending_board_access_request')],
            },
        ),
    ]
