# Generated by Django 5.1.5 on 2026-07-27 12:06

import PowerAdapterBlogs.image_validation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_boardaccessrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('scope', models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly')], default='yearly', max_length=16, verbose_name='周期')),
                ('year', models.PositiveSmallIntegerField(verbose_name='年份')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='月份')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='boards.board', verbose_name='板块')),
            ],
            options={
                'verbose_name': 'Apple Music 月度快照',
                'verbose_name_plural': 'Apple Music 月度快照',
                'ordering': ['-year', '-month'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, verbose_name='指标')),
                ('value', models.CharField(max_length=64, verbose_name='值')),
                ('unit', models.CharField(blank=True, max_length=16, verbose_name='单位')),
                ('kind', models.CharField(blank=True, max_length=32, verbose_name='类型')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='boards.applesnapshot', verbose_name='快照')),
            ],
            options={
                'verbose_name': 'Apple Music 条目',
                'verbose_name_plural': 'Apple Music 条目',
                'ordering': ['display_order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodingExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('title', models.CharField(max_length=128, verbose_name='实验名')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='boards.board', verbose_name='板块')),
            ],
            options={
                'verbose_name': '小型实验',
                'verbose_name_plural': '小型实验',
                'ordering': ['-date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CodingPrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='序号')),
                ('title', models.CharField(max_length=64, verbose_name='原则标题')),
                ('body', models.TextField(blank=True, verbose_name='原则正文')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principles', to='boards.board', verbose_name='板块')),
            ],
            options={
                'verbose_name': '编码原则',
                'verbose_name_plural': '编码原则',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CodingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='序号')),
                ('name', models.CharField(max_length=64, verbose_name='项目名')),
                ('description', models.TextField(blank=True, verbose_name='简述')),
                ('stack', models.CharField(blank=True, max_length=128, verbose_name='技术栈')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年份')),
                ('status', models.CharField(blank=True, max_length=32, verbose_name='状态')),
                ('url', models.URLField(blank=True, verbose_name='链接')),
                ('is_active', models.BooleanField(default=True, verbose_name='展示')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='boards.board', verbose_name='板块')),
            ],
            options={
                'verbose_name': '编码项目',
                'verbose_name_plural': '编码项目',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SkateHomie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_index', models.PositiveSmallIntegerField(verbose_name='节点编号')),
                ('name', models.CharField(max_length=64, verbose_name='成员名')),
                ('call_sign', models.CharField(blank=True, max_length=32, verbose_name='称呼')),
                ('location', models.CharField(blank=True, max_length=64, verbose_name='地区')),
                ('joined_at', models.DateField(verbose_name='加入时间')),
                ('role_label', models.CharField(blank=True, max_length=32, verbose_name='角色标签')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='skateboard/avatars/', validators=[PowerAdapterBlogs.image_validation.validate_uploaded_image], verbose_name='头像')),
                ('is_active', models.BooleanField(default=False, verbose_name='当前选中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('board', models.ForeignKey(help_text='固定为 skateboard', on_delete=django.db.models.deletion.CASCADE, related_name='homies', to='boards.board', verbose_name='板块')),
                ('memberships', models.ManyToManyField(blank=True, help_text='仅作展示/归属标注，不作为授权依据', related_name='homies', to='boards.boardmembership', verbose_name='关联成员')),
            ],
            options={
                'verbose_name': '滑板成员',
                'verbose_name_plural': '滑板成员',
                'ordering': ['node_index'],
            },
        ),
        migrations.CreateModel(
            name='SkateClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('title', models.CharField(max_length=80, verbose_name='动作名')),
                ('category', models.CharField(blank=True, choices=[('rotation', 'Rotation'), ('displacement', 'Displacement'), ('height', 'Height')], max_length=32, verbose_name='分类')),
                ('spot', models.CharField(blank=True, max_length=128, verbose_name='地点')),
                ('filmed_at', models.DateField(blank=True, null=True, verbose_name='拍摄日期')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='时长')),
                ('status', models.CharField(choices=[('landed', 'Landed'), ('unfinished', 'Unfinished'), ('wip', 'WIP'), ('failed', 'Failed')], default='landed', max_length=16, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('video_url', models.URLField(blank=True, verbose_name='视频')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='封面')),
                ('hud_type', models.CharField(blank=True, choices=[('arc', 'Arc'), ('speed', 'Speed'), ('measure', 'Measure'), ('ring', 'Ring')], max_length=16, verbose_name='HUD 类型')),
                ('hud_label', models.CharField(blank=True, max_length=64, verbose_name='HUD 文案')),
                ('timecode', models.CharField(blank=True, max_length=16, verbose_name='时间码')),
                ('is_public', models.BooleanField(default=True, verbose_name='公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('homie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='boards.skatehomie', verbose_name='成员')),
            ],
            options={
                'verbose_name': '滑板动作片段',
                'verbose_name_plural': '滑板动作片段',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SpotifySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('scope', models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly')], default='yearly', max_length=16, verbose_name='周期')),
                ('year', models.PositiveSmallIntegerField(verbose_name='年份')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='月份')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='boards.board', verbose_name='板块')),
            ],
            options={
                'verbose_name': 'Spotify 年度快照',
                'verbose_name_plural': 'Spotify 年度快照',
                'ordering': ['-year', '-month'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpotifyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, verbose_name='指标')),
                ('value', models.CharField(max_length=64, verbose_name='值')),
                ('unit', models.CharField(blank=True, max_length=16, verbose_name='单位')),
                ('kind', models.CharField(blank=True, max_length=32, verbose_name='类型')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='boards.spotifysnapshot', verbose_name='快照')),
            ],
            options={
                'verbose_name': 'Spotify 条目',
                'verbose_name_plural': 'Spotify 条目',
                'ordering': ['display_order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='skatehomie',
            constraint=models.UniqueConstraint(fields=('board', 'node_index'), name='unique_homie_node_per_board'),
        ),
    ]
