# Generated by Django 5.1.5 on 2026-07-27 18:17

import boards.models
import django.db.models.deletion
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_musicentry_value2_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applesnapshot',
            name='board',
            field=models.ForeignKey(default=functools.partial(boards.models._board_for_slug, *('music',), **{}), help_text='由模型类型固定为 music，不可手动选择', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='boards.board', verbose_name='板块'),
        ),
        migrations.AlterField(
            model_name='codingexperiment',
            name='board',
            field=models.ForeignKey(default=functools.partial(boards.models._board_for_slug, *('coding',), **{}), help_text='由模型类型固定为 coding，不可手动选择', on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='boards.board', verbose_name='板块'),
        ),
        migrations.AlterField(
            model_name='codingprinciple',
            name='board',
            field=models.ForeignKey(default=functools.partial(boards.models._board_for_slug, *('coding',), **{}), help_text='由模型类型固定为 coding，不可手动选择', on_delete=django.db.models.deletion.CASCADE, related_name='principles', to='boards.board', verbose_name='板块'),
        ),
        migrations.AlterField(
            model_name='codingproject',
            name='board',
            field=models.ForeignKey(default=functools.partial(boards.models._board_for_slug, *('coding',), **{}), help_text='由模型类型固定为 coding，不可手动选择', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='boards.board', verbose_name='板块'),
        ),
        migrations.AlterField(
            model_name='skatehomie',
            name='board',
            field=models.ForeignKey(default=functools.partial(boards.models._board_for_slug, *('skateboard',), **{}), help_text='由模型类型固定为 skateboard，不可手动选择', on_delete=django.db.models.deletion.CASCADE, related_name='homies', to='boards.board', verbose_name='板块'),
        ),
        migrations.AlterField(
            model_name='spotifysnapshot',
            name='board',
            field=models.ForeignKey(default=functools.partial(boards.models._board_for_slug, *('music',), **{}), help_text='由模型类型固定为 music，不可手动选择', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='boards.board', verbose_name='板块'),
        ),
    ]
