# Generated by Django 5.1.5 on 2026-07-27 19:31

import boards.models
import django.db.models.deletion
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_alter_applesnapshot_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applesnapshot',
            name='board',
        ),
        migrations.RemoveField(
            model_name='spotifyentry',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='spotifysnapshot',
            name='board',
        ),
        migrations.CreateModel(
            name='AppleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('scope', models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly')], default='yearly', max_length=16, verbose_name='周期')),
                ('year', models.PositiveSmallIntegerField(verbose_name='年份')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='月份')),
                ('label', models.CharField(max_length=64, verbose_name='指标')),
                ('value', models.CharField(max_length=64, verbose_name='值')),
                ('value2', models.CharField(blank=True, max_length=64, verbose_name='次值')),
                ('unit', models.CharField(blank=True, max_length=16, verbose_name='单位')),
                ('kind', models.CharField(blank=True, max_length=32, verbose_name='类型')),
                ('note', models.TextField(blank=True, verbose_name='注记')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('board', models.ForeignKey(default=functools.partial(boards.models._board_for_slug, *('music',), **{}), help_text='由模型类型固定为 music，不可手动选择', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='boards.board', verbose_name='板块')),
            ],
            options={
                'verbose_name': 'Apple Music 记录',
                'verbose_name_plural': 'Apple Music 记录',
                'ordering': ['-year', '-month', 'display_order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpotifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('scope', models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly')], default='yearly', max_length=16, verbose_name='周期')),
                ('year', models.PositiveSmallIntegerField(verbose_name='年份')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='月份')),
                ('label', models.CharField(max_length=64, verbose_name='指标')),
                ('value', models.CharField(max_length=64, verbose_name='值')),
                ('value2', models.CharField(blank=True, max_length=64, verbose_name='次值')),
                ('unit', models.CharField(blank=True, max_length=16, verbose_name='单位')),
                ('kind', models.CharField(blank=True, max_length=32, verbose_name='类型')),
                ('note', models.TextField(blank=True, verbose_name='注记')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('board', models.ForeignKey(default=functools.partial(boards.models._board_for_slug, *('music',), **{}), help_text='由模型类型固定为 music，不可手动选择', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='boards.board', verbose_name='板块')),
            ],
            options={
                'verbose_name': 'Spotify 记录',
                'verbose_name_plural': 'Spotify 记录',
                'ordering': ['-year', '-month', 'display_order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AppleEntry',
        ),
        migrations.DeleteModel(
            name='AppleSnapshot',
        ),
        migrations.DeleteModel(
            name='SpotifyEntry',
        ),
        migrations.DeleteModel(
            name='SpotifySnapshot',
        ),
    ]
