# Generated by Django 5.1.5 on 2026-07-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_merge_music_snapshot_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skatehomie',
            name='is_active',
        ),
    ]
