# Generated by Django 5.1.5 on 2026-07-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_remove_homie_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='skatehomie',
            name='stance',
            field=models.CharField(choices=[('regular', 'Regular'), ('goofy', 'Goofy')], default='regular', help_text='Regular=左脚在前，Goofy=右脚在前', max_length=16, verbose_name='站姿'),
        ),
    ]
