# Generated by Django 5.1.5 on 2026-08-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0010_add_homie_stance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="boardmembership",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterModelOptions(
            name="boardmembership",
            options={
                "ordering": ["board_id", "user_id"],
                "permissions": [
                    ("manage_all_board_memberships", "可管理所有板块成员"),
                ],
                "verbose_name": "板块成员",
                "verbose_name_plural": "板块成员",
            },
        ),
        migrations.CreateModel(
            name="BoardMembershipEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("granted", "授予"),
                            ("role_changed", "角色变更"),
                            ("deactivated", "停用"),
                            ("reactivated", "恢复"),
                            ("manager_transferred", "Manager 交接"),
                        ],
                        max_length=32,
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("access_request", "权限申请"),
                            ("self_service", "成员自助"),
                            ("dashboard", "Dashboard"),
                            ("super_admin", "Super admin break-glass"),
                            ("system_migration", "系统迁移"),
                        ],
                        max_length=32,
                        verbose_name="来源",
                    ),
                ),
                (
                    "previous_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("contributor", "投稿者"),
                            ("editor", "编辑者"),
                            ("reviewer", "审核者"),
                            ("manager", "板块管理员"),
                        ],
                        max_length=16,
                        verbose_name="原角色",
                    ),
                ),
                (
                    "new_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("contributor", "投稿者"),
                            ("editor", "编辑者"),
                            ("reviewer", "审核者"),
                            ("manager", "板块管理员"),
                        ],
                        max_length=16,
                        verbose_name="新角色",
                    ),
                ),
                (
                    "previous_is_active",
                    models.BooleanField(null=True, verbose_name="原启用状态"),
                ),
                (
                    "new_is_active",
                    models.BooleanField(verbose_name="新启用状态"),
                ),
                ("reason", models.TextField(blank=True, verbose_name="原因")),
                (
                    "board_id_snapshot",
                    models.PositiveBigIntegerField(verbose_name="板块 ID 快照"),
                ),
                (
                    "board_slug_snapshot",
                    models.SlugField(max_length=64, verbose_name="板块标识快照"),
                ),
                (
                    "user_id_snapshot",
                    models.PositiveBigIntegerField(verbose_name="用户 ID 快照"),
                ),
                (
                    "username_snapshot",
                    models.CharField(max_length=150, verbose_name="用户名快照"),
                ),
                (
                    "actor_id_snapshot",
                    models.PositiveBigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="操作者 ID 快照",
                    ),
                ),
                (
                    "actor_username_snapshot",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="操作者名称快照",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "access_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membership_events",
                        to="boards.boardaccessrequest",
                        verbose_name="关联申请",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_board_membership_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作者",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membership_events",
                        to="boards.board",
                        verbose_name="板块",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="boards.boardmembership",
                        verbose_name="板块成员关系",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="board_membership_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="成员",
                    ),
                ),
            ],
            options={
                "verbose_name": "板块成员事件",
                "verbose_name_plural": "板块成员事件",
                "ordering": ["-created_at", "-pk"],
                "default_permissions": ("view",),
                "indexes": [
                    models.Index(
                        fields=["board_id_snapshot", "-created_at"],
                        name="board_event_board_time_idx",
                    ),
                    models.Index(
                        fields=["user_id_snapshot", "-created_at"],
                        name="board_event_user_time_idx",
                    ),
                ],
            },
        ),
    ]
