# Generated by Django 5.1.5 on 2026-08-14 16:02

import boards.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_music_and_coding_index_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkateClipMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_key', models.UUIDField(default=uuid.uuid4, editable=False, help_text='服务端生成的稳定标识，决定派生文件目录名', verbose_name='资产键')),
                ('source_file', models.FileField(blank=True, help_text='仅服务端与 Worker 可读，永不生成公开 URL', max_length=255, storage=boards.models.skate_source_storage, upload_to=boards.models._skate_source_upload_to, verbose_name='私有原片')),
                ('main_file', models.FileField(blank=True, max_length=255, storage=boards.models.skate_delivery_storage, upload_to=boards.models._skate_main_upload_to, verbose_name='正式播放 WebM')),
                ('preview_file', models.FileField(blank=True, max_length=255, storage=boards.models.skate_delivery_storage, upload_to=boards.models._skate_preview_upload_to, verbose_name='红黑预览 WebM')),
                ('poster_file', models.ImageField(blank=True, max_length=255, storage=boards.models.skate_delivery_storage, upload_to=boards.models._skate_poster_upload_to, verbose_name='封面 WebP')),
                ('state', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=16, verbose_name='处理状态')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='FFprobe 权威时长，替代人工 duration', null=True, verbose_name='时长(毫秒)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='画面宽')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='画面高')),
                ('orientation', models.CharField(blank=True, choices=[('portrait', 'Portrait'), ('landscape', 'Landscape'), ('square', 'Square')], help_text='由探测宽高派生，不手工填写', max_length=16, verbose_name='画面方向')),
                ('frame_rate', models.CharField(blank=True, help_text='FFprobe r_frame_rate 文本（如 30000/1001），不解析为浮点', max_length=32, verbose_name='帧率')),
                ('source_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='原片字节数')),
                ('source_sha256', models.CharField(blank=True, help_text='重复检测、审计与处理输入一致性', max_length=64, verbose_name='原片 SHA-256')),
                ('pipeline_version', models.PositiveSmallIntegerField(default=1, help_text='风格/编码算法升级后可从原片批量重建派生资源', verbose_name='流水线版本')),
                ('error_code', models.CharField(blank=True, help_text='面向管理员的有界错误码，不含内部命令或路径', max_length=64, verbose_name='错误码')),
                ('error_detail', models.TextField(blank=True, help_text='有界诊断摘要；公开页面不得渲染此字段', verbose_name='错误详情')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('clip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='boards.skateclip', verbose_name='所属片段')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='仅审计用途；用户删除后媒体行保留', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_skate_media', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '片段媒体资产',
                'verbose_name_plural': '片段媒体资产',
            },
        ),
    ]
