# Generated by Django 5.1.5 on 2026-08-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_skateclipmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='skateclipmedia',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='Worker 原子领取时刻；超时未完成视为卡死可复位', null=True, verbose_name='领取时间'),
        ),
    ]
