# Generated by Django 5.1.5 on 2026-08-14 17:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_skateclipmedia_claimed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='skateclipmedia',
            name='claim_generation',
            field=models.PositiveIntegerField(default=0, help_text='每次领取或上传替换递增；Worker 写回时必须匹配此值', verbose_name='领取代次'),
        ),
        migrations.AddField(
            model_name='skateclipmedia',
            name='claim_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='每次领取生成新令牌；写回时必须匹配，防止 stale Worker 覆盖', verbose_name='领取令牌'),
        ),
    ]
