# Generated by Django 5.1.5 on 2026-08-28 02:42

import PowerAdapterBlogs.image_validation
import boards.models
import django.db.models.deletion
import functools
import unicodedata
from django.db import migrations, models


def link_existing_artist_records(apps, schema_editor):
    Board = apps.get_model("boards", "Board")
    MusicArtist = apps.get_model("boards", "MusicArtist")
    SpotifyRecord = apps.get_model("boards", "SpotifyRecord")
    AppleRecord = apps.get_model("boards", "AppleRecord")
    try:
        board = Board.objects.get(slug="music")
    except Board.DoesNotExist:
        return

    artists = {}
    for model, url_field in (
        (SpotifyRecord, "spotify_url"),
        (AppleRecord, "apple_music_url"),
    ):
        records = model.objects.filter(
            board=board,
            kind__in=("top_artist", "period_artist", "core_artist"),
        )
        for record in records.iterator():
            name = " ".join(unicodedata.normalize("NFKC", record.label).split())
            key = name.casefold()
            artist = artists.get(key)
            if artist is None:
                artist, _ = MusicArtist.objects.get_or_create(
                    board=board,
                    normalized_name=key,
                    defaults={"name": name},
                )
                artists[key] = artist
            if record.external_url and not getattr(artist, url_field):
                setattr(artist, url_field, record.external_url)
                artist.save(update_fields=[url_field, "updated_at"])
            record.artist_id = artist.pk
            record.save(update_fields=["artist"])


def unlink_artist_records(apps, schema_editor):
    apps.get_model("boards", "SpotifyRecord").objects.update(artist=None)
    apps.get_model("boards", "AppleRecord").objects.update(artist=None)


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_skateclip_location_and_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='艺人名')),
                ('normalized_name', models.CharField(editable=False, max_length=128)),
                ('avatar', models.ImageField(blank=True, upload_to=boards.models.board_content_cover_upload_to, validators=[PowerAdapterBlogs.image_validation.validate_uploaded_image], verbose_name='艺人头像')),
                ('spotify_url', models.URLField(blank=True, verbose_name='Spotify 链接')),
                ('apple_music_url', models.URLField(blank=True, verbose_name='Apple Music 链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('board', models.ForeignKey(default=functools.partial(boards.models._board_for_slug, *('music',), **{}), on_delete=django.db.models.deletion.CASCADE, related_name='music_artists', to='boards.board', verbose_name='板块')),
            ],
            options={
                'verbose_name': '音乐人',
                'verbose_name_plural': '音乐人',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='applerecord',
            name='artist',
            field=models.ForeignKey(blank=True, help_text='艺人排行建议选择；歌曲记录可选，用于统一音乐人身份。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='boards.musicartist', verbose_name='关联音乐人'),
        ),
        migrations.AddField(
            model_name='spotifyrecord',
            name='artist',
            field=models.ForeignKey(blank=True, help_text='艺人排行建议选择；歌曲记录可选，用于统一音乐人身份。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='boards.musicartist', verbose_name='关联音乐人'),
        ),
        migrations.AddConstraint(
            model_name='musicartist',
            constraint=models.UniqueConstraint(fields=('board', 'normalized_name'), name='unique_music_artist_name_per_board'),
        ),
        migrations.RunPython(link_existing_artist_records, unlink_artist_records),
    ]
