# Generated by Django 5.1.5 on 2025-09-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="image",
        ),
        migrations.AlterField(
            model_name="comment",
            name="nickname",
            field=models.CharField(
                blank=True, default="nickname", max_length=50, verbose_name="昵称"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.PositiveIntegerField(
                choices=[(0, "待审核"), (1, "已发布"), (2, "已拒绝"), (3, "已删除")],
                default=0,
                verbose_name="状态",
            ),
        ),
    ]
